#ifndef MODULEMANAGMENT_GLOBAL_H
#define MODULEMANAGMENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODULEMANAGMENT_LIBRARY)
#  define MODULEMANAGMENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODULEMANAGMENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODULEMANAGMENT_GLOBAL_H
