#ifndef NEXUSCOORDINATOR_GLOBAL_H
#define NEXUSCOORDINATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NEXUSCOORDINATOR_LIBRARY)
#  define NEXUSCOORDINATORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NEXUSCOORDINATORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NEXUSCOORDINATOR_GLOBAL_H
