#ifndef CONTROLSERVER_GLOBAL_H
#define CONTROLSERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONTROLSERVER_LIBRARY)
#  define CONTROLSERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONTROLSERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTROLSERVER_GLOBAL_H
